spring:
  datasource:
    url: jdbc:mysql://39.106.50.22:3306/flowable-spring-boot?characterEncoding=UTF-8
    username: root
    password: 5996042q
server:
  port: 8081
flowable:
#关闭定时任务JOB
  async-executor-activate: false

